imports:
    - { resource: config_behat.yml }
    - { resource: ../../tests/back/Acceptance/Resources/config/pim/repositories.yml }
    - { resource: ../../src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Acceptance/Resources/config/pim/queries.yml }
    - { resource: ../../src/Akeneo/Analytics/Bundle/tests/Acceptance/Resources/config/inMemory/queries.yml }
