services:
    pim_analytics.storage.completeness_widget_query:
        class: 'Akeneo\Analytics\Bundle\Storage\ElasticsearchAndSql\CompletenessWidget\CompletenessWidgetQuery'
        arguments:
            - '@database_connection'
            - '@akeneo_elasticsearch.client.product'
            - 'pim_catalog_product'
